# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
script: ./test.sh
