# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_SECURE_ENV_VARS
  - cd codescan
  - ./test.sh
